import 'package:ff_golden_presenter/ff_golden_presenter.dart';
import 'package:test/test.dart';

void main() {
  test('renders a semantic report with portable image paths and escaped text',
      () {
    final catalog = GoldenCatalog(
      scenarios: [
        GoldenScenario(
          pathSegments: const ['auth', 'sign_in'],
          images: const [
            GoldenImage(
              fileName: 'iphone_15[dark](en-US).png',
              path:
                  '/project/test/auth/golden/sign_in/iphone_15[dark](en-US).png',
              device: 'iphone_15',
              theme: 'dark',
              locale: 'en-US',
              captureName: 'empty',
              textScale: 1.5,
              direction: 'rtl',
              directionMode: 'rtl',
              platform: 'iOS',
              brightness: 'dark',
              highContrast: true,
              status: GoldenImageStatus.failed,
              durationMs: 12.5,
              failurePhase: 'capture',
              error: 'Mismatch <unsafe>',
              extension: 'png',
            ),
          ],
        ),
      ],
    );

    final result = HtmlReportRenderer(
      outputPath: '/project/report.html',
      title: 'App <goldens>',
    ).render(catalog);

    expect(result.html, startsWith('<!doctype html>'));
    expect(result.html, contains('<main class="report-shell">'));
    expect(result.html, contains('App &lt;goldens&gt;'));
    expect(result.html, contains('auth / sign_in'));
    expect(result.html, contains('data-device="iphone_15"'));
    expect(result.html, contains('data-theme="dark"'));
    expect(result.html, contains('data-capture="empty"'));
    expect(result.html, contains('data-text-scale="1.5"'));
    expect(result.html, contains('data-direction="rtl"'));
    expect(result.html, contains('data-platform="iOS"'));
    expect(result.html, contains('data-brightness="dark"'));
    expect(result.html, contains('data-contrast="high"'));
    expect(result.html, contains('data-status="failed"'));
    expect(result.html, contains('id="status-filter"'));
    expect(result.html, contains('Failed during capture'));
    expect(result.html, contains('Mismatch &lt;unsafe&gt;'));
    expect(result.html, contains('test/auth/golden/sign_in/'));
    expect(result.html, contains('iphone_15%5Bdark%5D'));
    expect(result.html, isNot(contains('/project/test')));
    expect(result.html, contains('id="lightbox"'));
    expect(result.html, contains('id="search"'));
    expect(result.html, contains('id="theme-toggle"'));
    expect(result.html, contains('ff-golden-presenter-theme'));
    expect(result.html, contains('Made with support from'));
    expect(
      result.html,
      contains(
        'href="https://aso.dev/?utm_source=ff_golden&amp;utm_medium=referral"',
      ),
    );
    expect(result.html, contains('rel="sponsored noopener"'));
    expect(result.html, contains('target="_blank"'));
    expect(RegExp(r'[ \t]+$', multiLine: true).hasMatch(result.html), isFalse);
  });

  test('can omit ASO.dev support attribution while retaining generator credit',
      () {
    final result = HtmlReportRenderer(
      outputPath: '/project/report.html',
      showSupportAttribution: false,
    ).render(GoldenCatalog(scenarios: const []));

    expect(result.html, isNot(contains('aso.dev')));
    expect(result.html, isNot(contains('Made with support from')));
    expect(result.html, contains('Generated by'));
    expect(result.html, contains('FF Golden Presenter'));
  });

  test('renders a useful empty report', () {
    final result = HtmlReportRenderer(
      outputPath: '/project/report.html',
    ).render(GoldenCatalog(scenarios: const []));

    expect(result.html, contains('No images were found'));
    expect(result.html, contains('<dd>0</dd>'));
  });
}
